<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/bpm/configuration" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_8kqAYPkLEe-sVKVci2O3GA" name="MiDiagrama" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_8kqAYfkLEe-sVKVci2O3GA" name="Hospitalización Curatio">
      <elements xmi:type="process:Lane" xmi:id="_8kqAYvkLEe-sVKVci2O3GA" name="Paciente" actor="_vnxdwPkMEe-sVKVci2O3GA">
        <elements xmi:type="process:StartEvent" xmi:id="_8kqAY_kLEe-sVKVci2O3GA" name="Ingreso del paciente" outgoing="_o2cpAPkOEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8kqAZPkLEe-sVKVci2O3GA" name="Ingreso del paciente" content="Ingreso del paciente" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8kqAZfkLEe-sVKVci2O3GA" name="Ingreso del paciente" content="Ingreso del paciente" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8kqAZvkLEe-sVKVci2O3GA" name="Ingreso del paciente" content="Ingreso del paciente" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateThrowMessageEvent" xmi:id="_fwH9sPkOEe-sVKVci2O3GA" name="Solicitar Aprobación" outgoing="_z89qcPkOEe-sVKVci2O3GA" incoming="_Uj98UPnUEe-6NbZI5Pt9YA" outgoingMessages="_frgBwPkhEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TxVQcvkOEe-sVKVci2O3GA" name="Solicitar validación del usuario" content="Solicitar validación del usuario" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TxVQcfkOEe-sVKVci2O3GA" name="Validar usuario" content="Validar usuario" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TxVQc_kOEe-sVKVci2O3GA" name="Validar usuario para atencion" content="Validar usuario para atencion" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_frfasPkhEe-sVKVci2O3GA" documentation="Se solicita validar el paciente" name="¿Solicitud de validación del paciente?">
            <correlation xmi:type="process:Correlation" xmi:id="_frfasfkhEe-sVKVci2O3GA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_frfasvkhEe-sVKVci2O3GA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_frfas_khEe-sVKVci2O3GA" name="Aseguradora" content="Aseguradora" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_frfatPkhEe-sVKVci2O3GA" name="Recepción solicitud" content="Recepción solicitud" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_frfatfkhEe-sVKVci2O3GA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_CRvGoPnKEe-LY4Y-wpuNyg">
                <expressions xmi:type="expression:Expression" xmi:id="_CRvGofnKEe-LY4Y-wpuNyg" name="solicitudPaciente" content="solicitudPaciente" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_CRvGovnKEe-LY4Y-wpuNyg" name="solicitudPaciente" content="solicitudPaciente.numberId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_b2o3oPqjEe-6RI7d5mZgpg" name="solicitudPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.SolicitudPaciente"/>
                </expressions>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:IntermediateCatchMessageEvent" xmi:id="_xvwMAPkOEe-sVKVci2O3GA" name="Recepcion Respuesta" outgoing="_gvs7gPqnEe-6RI7d5mZgpg" incoming="_z89qcPkOEe-sVKVci2O3GA" event="El usuario se encuentra o no asegurado" incomingMessag="_3Lcw8PkUEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s-qbkvkOEe-sVKVci2O3GA" name="Recepción de asegurado" content="Recepción de asegurado" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s-qbkfkOEe-sVKVci2O3GA" name="El usuario se encuentra asegurado" content="El usuario se encuentra asegurado" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s-qbk_kOEe-sVKVci2O3GA" name="Validar usuario asegurado" content="Validar usuario asegurado" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_zJ85IPkOEe-sVKVci2O3GA"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_tC4jQPnJEe-LY4Y-wpuNyg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_tC5xYfnJEe-LY4Y-wpuNyg" name="decisionaseguradora" content="decisionaseguradora" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_PVyN8PnZEe-6NbZI5Pt9YA" name="decisionaseguradora" dataType="_8kqAjPkLEe-sVKVci2O3GA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_tC5xYPnJEe-LY4Y-wpuNyg" name="asegurado" content="asegurado" type="MESSAGE_ID_TYPE" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_tC4jQfnJEe-LY4Y-wpuNyg" type="ASSIGNMENT"/>
          </messageContent>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Y5W2APkVEe-sVKVci2O3GA" name="Validar nuevamente, atender paciente" incoming="_l0dagPkVEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Y5XdEfkVEe-sVKVci2O3GA" name="Validar nuevamente, atender paciente" content="Validar nuevamente, atender paciente" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Y5XdEPkVEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Y5XdEvkVEe-sVKVci2O3GA" name="Validar nuevamente, atender paciente" content="Validar nuevamente, atender paciente" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_uk3hYPkvEe-sVKVci2O3GA" name="Realizar solicitud" outgoing="_Uj98UPnUEe-6NbZI5Pt9YA" incoming="_o2cpAPkOEe-sVKVci2O3GA" actor="_vnxdwPkMEe-sVKVci2O3GA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_i01o4vkvEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_i01o4fkvEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_i01o4_kvEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_GG12k_kzEe-sVKVci2O3GA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_GG12lPkzEe-sVKVci2O3GA" name="solicitudPaciente" content="solicitudPaciente" type="TYPE_VARIABLE" returnType="com.company.model.SolicitudPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_GG12lfkzEe-sVKVci2O3GA" name="solicitudPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.SolicitudPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_GG12lvkzEe-sVKVci2O3GA" name="solicitudPacienteInput.typeId" content="solicitudPacienteInput?.typeId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_GG12l_kzEe-sVKVci2O3GA" name="solicitudPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_GG12mPkzEe-sVKVci2O3GA" type="JAVA_METHOD" expression="setTypeId">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_GG12mfkzEe-sVKVci2O3GA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_GG12mvkzEe-sVKVci2O3GA" name="solicitudPaciente" content="solicitudPaciente" type="TYPE_VARIABLE" returnType="com.company.model.SolicitudPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_GG12m_kzEe-sVKVci2O3GA" name="solicitudPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.SolicitudPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_GG12nPkzEe-sVKVci2O3GA" name="solicitudPacienteInput.numberId" content="solicitudPacienteInput?.numberId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_GG12nfkzEe-sVKVci2O3GA" name="solicitudPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_GG2doPkzEe-sVKVci2O3GA" type="JAVA_METHOD" expression="setNumberId">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_i01o5PkvEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_i01o5fkvEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_i01o5vkvEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_i01o6PkvEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_i01o5_kvEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_uk4IcPkvEe-sVKVci2O3GA">
            <targetForm xmi:type="expression:Expression" xmi:id="_w4qwAPkvEe-sVKVci2O3GA" name="SolicitudPaciente" content="73b08f70-a632-49a2-8308-6977956ad95d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_uk3hafkvEe-sVKVci2O3GA">
            <inputs xmi:type="process:ContractInput" xmi:id="_GG12kPkzEe-sVKVci2O3GA" name="solicitudPacienteInput" type="COMPLEX" dataReference="solicitudPaciente" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_GG12kfkzEe-sVKVci2O3GA" name="typeId" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_GG12kvkzEe-sVKVci2O3GA" name="numberId" type="INTEGER" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_uk4IcvkvEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ipYz8PmJEe-fP-Ja3oJY_g" name="¿Se ha aprobado la solicirtud?" outgoing="_l0dagPkVEe-sVKVci2O3GA _Z-mfYPncEe-6NbZI5Pt9YA" incoming="_gvs7gPqnEe-6RI7d5mZgpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MtnR4vkVEe-sVKVci2O3GA" name="¿Se ha aprobado la solicitud?" content="¿Se ha aprobado la solicitud?" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MtnR4fkVEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MtnR4_kVEe-sVKVci2O3GA" name="validar aprobacion de solicitud" content="validar aprobacion de solicitud" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Mw29sPkWEe-sVKVci2O3GA" name="MedicoUrgencias" actor="_U8x2QPkWEe-sVKVci2O3GA">
        <elements xmi:type="process:EndSignalEvent" xmi:id="_5aXNoPkWEe-sVKVci2O3GA" name="Alta del paciente 1" signalCode="Facturación" incoming="_Enje0PkXEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5aXNovkWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5aXNofkWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5aXNo_kWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Lt7roPkXEe-sVKVci2O3GA" name="Evaluar paciente" outgoing="_6kMKMPkbEe-sVKVci2O3GA" incoming="_O0RKcPkXEe-sVKVci2O3GA" overrideActorsOfTheLane="false" priority="3">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JcM5kfkXEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JcM5kPkXEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JcM5kvkXEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="__ln5JfneEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="__ln5JvneEe-6NbZI5Pt9YA" name="evaluarPaciente" content="evaluarPaciente" type="TYPE_VARIABLE" returnType="com.company.model.EvaluarPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__ln5J_neEe-6NbZI5Pt9YA" name="evaluarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.EvaluarPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="__ln5KPneEe-6NbZI5Pt9YA" name="evaluarPacienteInput.sintomas" content="evaluarPacienteInput?.sintomas" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="__ln5KfneEe-6NbZI5Pt9YA" name="evaluarPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="__ln5KvneEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setSintomas">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="__ln5K_neEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="__ln5LPneEe-6NbZI5Pt9YA" name="evaluarPaciente" content="evaluarPaciente" type="TYPE_VARIABLE" returnType="com.company.model.EvaluarPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__ln5LfneEe-6NbZI5Pt9YA" name="evaluarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.EvaluarPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="__ln5LvneEe-6NbZI5Pt9YA" name="evaluarPacienteInput.descripcion" content="evaluarPacienteInput?.descripcion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="__ln5L_neEe-6NbZI5Pt9YA" name="evaluarPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="__ln5MPneEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setDescripcion">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="__ln5MfneEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="__ln5MvneEe-6NbZI5Pt9YA" name="evaluarPaciente" content="evaluarPaciente" type="TYPE_VARIABLE" returnType="com.company.model.EvaluarPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__ln5M_neEe-6NbZI5Pt9YA" name="evaluarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.EvaluarPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="__ln5NPneEe-6NbZI5Pt9YA" name="evaluarPacienteInput.enfermedadSospecha" content="evaluarPacienteInput?.enfermedadSospecha" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="__ln5NfneEe-6NbZI5Pt9YA" name="evaluarPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="__ln5NvneEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setEnfermedadSospecha">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="__ln5N_neEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="__ln5OPneEe-6NbZI5Pt9YA" name="evaluarPaciente" content="evaluarPaciente" type="TYPE_VARIABLE" returnType="com.company.model.EvaluarPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__ln5OfneEe-6NbZI5Pt9YA" name="evaluarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.EvaluarPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="__ln5OvneEe-6NbZI5Pt9YA" name="evaluarPacienteInput.medicamentos" content="evaluarPacienteInput?.medicamentos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="__ln5O_neEe-6NbZI5Pt9YA" name="evaluarPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="__ln5PPneEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setMedicamentos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JcM5k_kXEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JcM5lPkXEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JcM5lfkXEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JcM5l_kXEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JcM5lvkXEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Lt7rqvkXEe-sVKVci2O3GA">
            <targetForm xmi:type="expression:Expression" xmi:id="_Af7lQPnfEe-6NbZI5Pt9YA" name="EvaluarPaciente" content="05e6e29b-78a3-497a-a4b3-eff1529923f6" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Lt7rqfkXEe-sVKVci2O3GA">
            <inputs xmi:type="process:ContractInput" xmi:id="__ln5IPneEe-6NbZI5Pt9YA" name="evaluarPacienteInput" type="COMPLEX" dataReference="evaluarPaciente" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="__ln5IfneEe-6NbZI5Pt9YA" name="sintomas" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="__ln5IvneEe-6NbZI5Pt9YA" name="descripcion" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="__ln5I_neEe-6NbZI5Pt9YA" name="enfermedadSospecha" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="__ln5JPneEe-6NbZI5Pt9YA" name="medicamentos" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Lt7rrPkXEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_7USKYPkbEe-sVKVci2O3GA" name="Realizar laboratorios" outgoing="_GWuW4PpKEe-fE4P_wlxD9A" incoming="_6kMKMPkbEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3ohDQfkbEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3ohDQPkbEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3ohDQvkbEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_JMi-APoJEe-u9f6z6Vxoeg" name="resultadosLaboratorio" dataType="_8kqAjPkLEe-sVKVci2O3GA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_JMi-AfoJEe-u9f6z6Vxoeg" name="true" content="true" returnType="java.lang.Boolean"/>
          </data>
          <data xmi:type="process:Data" xmi:id="_bd3qYPo3Ee-fE4P_wlxD9A" name="necesarioCirugia" dataType="_8kqAjPkLEe-sVKVci2O3GA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_bd3qYfo3Ee-fE4P_wlxD9A" content="" returnType="java.lang.Boolean"/>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3ohDQ_kbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3ohDRPkbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3ohDRfkbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3ohDR_kbEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3ohDRvkbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_0KhecPpEEe-fE4P_wlxD9A" subprocessTarget="examinarMuestras" assignationType="Data">
            <processSource xmi:type="expression:Expression" xmi:id="_0KhecfpEEe-fE4P_wlxD9A" name="resultadosLabo" content="resultadosLabo" type="TYPE_VARIABLE" returnType="com.company.model.ExaminarMuestras">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1Mgf4PpEEe-fE4P_wlxD9A" name="resultadosLabo" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras"/>
            </processSource>
          </inputMappings>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_7USKZPkbEe-sVKVci2O3GA" name="Laboratorio" content="Laboratorio" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_7USKZfkbEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_WjDzYPkdEe-sVKVci2O3GA" name="Realizar tratamiento" outgoing="_dWPXYPkdEe-sVKVci2O3GA" incoming="_HiQGo_kdEe-sVKVci2O3GA" type="STANDARD" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HiPfkvkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HiPfkfkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HiPfk_kdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_RtM3pfnhEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RtM3pvnhEe-6NbZI5Pt9YA" name="tratamiento" content="tratamiento" type="TYPE_VARIABLE" returnType="com.company.model.Tratamiento">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RtM3p_nhEe-6NbZI5Pt9YA" name="tratamiento" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.Tratamiento"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RtM3qPnhEe-6NbZI5Pt9YA" name="tratamientoInput.id" content="tratamientoInput?.id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RtM3qfnhEe-6NbZI5Pt9YA" name="tratamientoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RtM3qvnhEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setId">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_RtM3q_nhEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RtM3rPnhEe-6NbZI5Pt9YA" name="tratamiento" content="tratamiento" type="TYPE_VARIABLE" returnType="com.company.model.Tratamiento">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RtM3rfnhEe-6NbZI5Pt9YA" name="tratamiento" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.Tratamiento"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RtM3rvnhEe-6NbZI5Pt9YA" name="tratamientoInput.nombreTratamiento" content="tratamientoInput?.nombreTratamiento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RtM3r_nhEe-6NbZI5Pt9YA" name="tratamientoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RtM3sPnhEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setNombreTratamiento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_RtM3sfnhEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RtM3svnhEe-6NbZI5Pt9YA" name="tratamiento" content="tratamiento" type="TYPE_VARIABLE" returnType="com.company.model.Tratamiento">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RtM3s_nhEe-6NbZI5Pt9YA" name="tratamiento" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.Tratamiento"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RtM3tPnhEe-6NbZI5Pt9YA" name="tratamientoInput.numeroDias" content="tratamientoInput?.numeroDias" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RtM3tfnhEe-6NbZI5Pt9YA" name="tratamientoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RtM3tvnhEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setNumeroDias">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_RtM3t_nhEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RtM3uPnhEe-6NbZI5Pt9YA" name="tratamiento" content="tratamiento" type="TYPE_VARIABLE" returnType="com.company.model.Tratamiento">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RtM3ufnhEe-6NbZI5Pt9YA" name="tratamiento" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.Tratamiento"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RtM3uvnhEe-6NbZI5Pt9YA" name="tratamientoInput.resultadoFinal" content="tratamientoInput?.resultadoFinal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RtM3u_nhEe-6NbZI5Pt9YA" name="tratamientoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RtM3vPnhEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setResultadoFinal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HiPflPkdEe-sVKVci2O3GA" name="¿Paciente tratado con exito?" content="¿Paciente tratado con exito?" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HiPflfkdEe-sVKVci2O3GA" name="2" content="2" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HiPflvkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HiPfmPkdEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HiPfl_kdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_WjEaefkdEe-sVKVci2O3GA">
            <targetForm xmi:type="expression:Expression" xmi:id="_SBbbMPnhEe-6NbZI5Pt9YA" name="Tratamiento" content="ea71c8df-8d3f-4657-9a2a-ff61493b80d9" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_WjEaePkdEe-sVKVci2O3GA">
            <inputs xmi:type="process:ContractInput" xmi:id="_RtM3oPnhEe-6NbZI5Pt9YA" name="tratamientoInput" type="COMPLEX" dataReference="tratamiento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_RtM3ofnhEe-6NbZI5Pt9YA" name="id" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_RtM3ovnhEe-6NbZI5Pt9YA" name="nombreTratamiento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_RtM3o_nhEe-6NbZI5Pt9YA" name="numeroDias" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_RtM3pPnhEe-6NbZI5Pt9YA" name="resultadoFinal" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_WjEae_kdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndSignalEvent" xmi:id="_aUdocPkdEe-sVKVci2O3GA" name="Alta del paciente 2" signalCode="Facturación" incoming="_dWPXYPkdEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aUePgfkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aUePgPkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aUePgvkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_fXj5cPkeEe-sVKVci2O3GA" name="Esperar resultados" outgoing="_eCjHEPoKEe-u9f6z6Vxoeg" incoming="_4t1p4PpKEe-fE4P_wlxD9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fXj5cvkeEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fXj5cfkeEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fXj5c_keEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_jtZw8PkhEe-sVKVci2O3GA" name="00:00:01" content="1000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_bkmz4PncEe-6NbZI5Pt9YA" name="Clasificar Paciente" outgoing="_ZZ4owPncEe-6NbZI5Pt9YA" incoming="_Z-mfYPncEe-6NbZI5Pt9YA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VyGpwvncEe-6NbZI5Pt9YA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VyGpwfncEe-6NbZI5Pt9YA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VyGpw_ncEe-6NbZI5Pt9YA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_rRGh9PncEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rRGh9fncEe-6NbZI5Pt9YA" name="clasificarPaciente" content="clasificarPaciente" type="TYPE_VARIABLE" returnType="com.company.model.ClasificarPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rRGh9vncEe-6NbZI5Pt9YA" name="clasificarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ClasificarPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rRGh9_ncEe-6NbZI5Pt9YA" name="clasificarPacienteInput.pacienteId" content="clasificarPacienteInput?.pacienteId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rRGh-PncEe-6NbZI5Pt9YA" name="clasificarPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rRGh-fncEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setPacienteId">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rRGh-vncEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rRGh-_ncEe-6NbZI5Pt9YA" name="clasificarPaciente" content="clasificarPaciente" type="TYPE_VARIABLE" returnType="com.company.model.ClasificarPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rRGh_PncEe-6NbZI5Pt9YA" name="clasificarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ClasificarPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rRGh_fncEe-6NbZI5Pt9YA" name="clasificarPacienteInput.pacienteNombre" content="clasificarPacienteInput?.pacienteNombre" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rRGh_vncEe-6NbZI5Pt9YA" name="clasificarPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rRGh__ncEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setPacienteNombre">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rRGiAPncEe-6NbZI5Pt9YA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rRGiAfncEe-6NbZI5Pt9YA" name="clasificarPaciente" content="clasificarPaciente" type="TYPE_VARIABLE" returnType="com.company.model.ClasificarPaciente">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rRGiAvncEe-6NbZI5Pt9YA" name="clasificarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ClasificarPaciente"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rRGiA_ncEe-6NbZI5Pt9YA" name="clasificarPacienteInput.pacienteClasificacion" content="clasificarPacienteInput?.pacienteClasificacion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rRGiBPncEe-6NbZI5Pt9YA" name="clasificarPacienteInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rRGiBfncEe-6NbZI5Pt9YA" type="JAVA_METHOD" expression="setPacienteClasificacion">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VyGpxPncEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VyGpxfncEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VyGpxvncEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VyGpyPncEe-6NbZI5Pt9YA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VyGpx_ncEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_bkna9_ncEe-6NbZI5Pt9YA">
            <targetForm xmi:type="expression:Expression" xmi:id="_bkna-PncEe-6NbZI5Pt9YA" name="ClasificarPaciente" content="579b8ac4-6c6f-49e2-93d2-99879cf20051" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_bkna9vncEe-6NbZI5Pt9YA">
            <inputs xmi:type="process:ContractInput" xmi:id="_rRGh8PncEe-6NbZI5Pt9YA" name="clasificarPacienteInput" type="COMPLEX" dataReference="clasificarPaciente" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_rRGh8fncEe-6NbZI5Pt9YA" name="pacienteId" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rRGh8vncEe-6NbZI5Pt9YA" name="pacienteNombre" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rRGh8_ncEe-6NbZI5Pt9YA" name="pacienteClasificacion" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_bkna-fncEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_PtIksPneEe-6NbZI5Pt9YA" name="¿Urgencia Prioritaria?" outgoing="_xUAKgPkWEe-sVKVci2O3GA _O0RKcPkXEe-sVKVci2O3GA" incoming="_ZZ4owPncEe-6NbZI5Pt9YA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nZsdgfkWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nZsdgPkWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nZsdgvkWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_zeHNYPnhEe-6NbZI5Pt9YA" name="¿Se necesita cirugia?" outgoing="_HiQGo_kdEe-sVKVci2O3GA _qDshcPkdEe-sVKVci2O3GA" incoming="_eCjHEPoKEe-u9f6z6Vxoeg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4b7AsfkcEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4b7AsPkcEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4b7AsvkcEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_iq8acPpKEe-fE4P_wlxD9A" name="Realizar imagenes dianosticas" outgoing="_4t1p4PpKEe-fE4P_wlxD9A" incoming="_GWuW4PpKEe-fE4P_wlxD9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__ClBEvkbEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__ClBEfkbEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__ClBE_kbEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__ClBFPkbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__ClBFfkbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__ClBFvkbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__ClBGPkbEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__ClBF_kbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_kLXrYPpKEe-fE4P_wlxD9A" name="Remitir a cirugia" outgoing="_9fJ0kPkdEe-sVKVci2O3GA" incoming="_qDshcPkdEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mcct8fkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mcct8PkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mcct8vkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mcct8_kdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mcct9PkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mcct9fkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mcct9_kdEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mcct9vkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_uartIPpMEe-fE4P_wlxD9A" name="Consultar de manera externa" outgoing="_Enje0PkXEe-sVKVci2O3GA" incoming="_xUAKgPkWEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_siva8vkWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_siva8fkWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_siva8_kWEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_siva9PkWEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_siva9fkWEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_siva9vkWEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_siva-PkWEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_siva9_kWEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_2urmUPkdEe-sVKVci2O3GA" name="Hospitalario" actor="_4Jae8PkdEe-sVKVci2O3GA">
        <elements xmi:type="process:EndSignalEvent" xmi:id="_F7vmYPkeEe-sVKVci2O3GA" name="Alta del paciente 3" signalCode="Facturación" incoming="_dn0iAPpOEe-fE4P_wlxD9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F7wNcfkeEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F7wNcPkeEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F7wNcvkeEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_TC1_gPkeEe-sVKVci2O3GA" name="Tiempo de recuperacion" outgoing="_dn0iAPpOEe-fE4P_wlxD9A" incoming="_VXVKoPkeEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TC1_gvkeEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TC1_gfkeEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TC1_g_keEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_nwhBEPkhEe-sVKVci2O3GA" name="00:00:01" content="1000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_k0jLQPpKEe-fE4P_wlxD9A" name="Remitir a hospitalización" outgoing="_VXVKoPkeEe-sVKVci2O3GA" incoming="_9fJ0kPkdEe-sVKVci2O3GA" type="STANDARD">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7OZS4vkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7OZS4fkdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7OZS4_kdEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7OZS5PkdEe-sVKVci2O3GA" name="¿Paciente tratado ?" content="¿Paciente tratado ?" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7OZS5fkdEe-sVKVci2O3GA" name="2" content="2" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7OZS5vkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7OZS6PkdEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7OZS5_kdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_gE6-oPkyEe-sVKVci2O3GA" name="solicitudPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.SolicitudPaciente">
        <defaultValue xmi:type="expression:Expression" xmi:id="_gE6-ofkyEe-sVKVci2O3GA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_a0i7cPmFEe-fP-Ja3oJY_g" name="clasificarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ClasificarPaciente">
        <defaultValue xmi:type="expression:Expression" xmi:id="_a0i7cfmFEe-fP-Ja3oJY_g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_dTIBQPmGEe-fP-Ja3oJY_g" name="clasificacion" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.Clasificacion">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dTIBQfmGEe-fP-Ja3oJY_g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_H7zhkPmKEe-fP-Ja3oJY_g" name="asegurado" dataType="_8kqAjPkLEe-sVKVci2O3GA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_H7zhkfmKEe-fP-Ja3oJY_g" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_fC86IPnIEe-LY4Y-wpuNyg" name="pacienteAsegurado" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.PacienteAsegurado">
        <defaultValue xmi:type="expression:Expression" xmi:id="_fC86IfnIEe-LY4Y-wpuNyg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2o2X8PnJEe-LY4Y-wpuNyg" name="aseguradoBool" dataType="_8kqAjPkLEe-sVKVci2O3GA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_2o2X8fnJEe-LY4Y-wpuNyg" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_wG33sPnUEe-6NbZI5Pt9YA" name="enviosolicitud" dataType="_8kqAkfkLEe-sVKVci2O3GA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_wG33sfnUEe-6NbZI5Pt9YA" name="1030676576" content="1030676576"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_PVn14PnZEe-6NbZI5Pt9YA" name="decisionaseguradora" dataType="_8kqAjPkLEe-sVKVci2O3GA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_PVn14fnZEe-6NbZI5Pt9YA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_9xPxcPneEe-6NbZI5Pt9YA" name="evaluarPaciente" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.EvaluarPaciente">
        <defaultValue xmi:type="expression:Expression" xmi:id="_9xPxcfneEe-6NbZI5Pt9YA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_QAp2QPnhEe-6NbZI5Pt9YA" name="tratamiento" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.Tratamiento">
        <defaultValue xmi:type="expression:Expression" xmi:id="_QAp2QfnhEe-6NbZI5Pt9YA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Uckx4Po3Ee-fE4P_wlxD9A" name="resultadosLabo" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Uckx4fo3Ee-fE4P_wlxD9A" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_8kqAdPkLEe-sVKVci2O3GA">
        <targetForm xmi:type="expression:Expression" xmi:id="_37ThwvkuEe-sVKVci2O3GA" name="Hospitalizacion" content="ffb1851c-f313-448e-9687-0294602be55f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_8kqAdvkLEe-sVKVci2O3GA">
        <targetForm xmi:type="expression:Expression" xmi:id="_hFTIcPkwEe-sVKVci2O3GA" name="ResumenHospitalizacion" content="dd7483a0-5a97-4c7b-b642-3ad8734b323f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_o2cpAPkOEe-sVKVci2O3GA" target="_uk3hYPkvEe-sVKVci2O3GA" source="_8kqAY_kLEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_o2dQEPkOEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_o2dQEfkOEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_z89qcPkOEe-sVKVci2O3GA" target="_xvwMAPkOEe-sVKVci2O3GA" source="_fwH9sPkOEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_z89qcfkOEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_z8-RgPkOEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l0dagPkVEe-sVKVci2O3GA" name="No" target="_Y5W2APkVEe-sVKVci2O3GA" source="_ipYz8PmJEe-fP-Ja3oJY_g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l0dagfkVEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_YSbAIPmJEe-fP-Ja3oJY_g" name="ValidateBool" content="decisionaseguradora  != true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_TGdqQPnZEe-6NbZI5Pt9YA" name="decisionaseguradora" dataType="_8kqAjPkLEe-sVKVci2O3GA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xUAKgPkWEe-sVKVci2O3GA" name="No" target="_uartIPpMEe-fE4P_wlxD9A" source="_PtIksPneEe-6NbZI5Pt9YA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xUAKgfkWEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xUAKgvkWEe-sVKVci2O3GA" name="ValidatePatientData" content="clasificacionDAO.findByClasificacionNombre('Nivel 5', 1, 1)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="expression:Expression" xmi:id="_nHQQUPnfEe-6NbZI5Pt9YA" name="clasificacionDAO" content="clasificacionDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.ClasificacionDAO" returnTypeFixed="true"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Enje0PkXEe-sVKVci2O3GA" target="_5aXNoPkWEe-sVKVci2O3GA" source="_uartIPpMEe-fE4P_wlxD9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Enje0fkXEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Enje0vkXEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_O0RKcPkXEe-sVKVci2O3GA" name="Si" target="_Lt7roPkXEe-sVKVci2O3GA" source="_PtIksPneEe-6NbZI5Pt9YA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_O0RKcfkXEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_O0RKcvkXEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6kMKMPkbEe-sVKVci2O3GA" target="_7USKYPkbEe-sVKVci2O3GA" source="_Lt7roPkXEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6kMKMfkbEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6kMKMvkbEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HiQGo_kdEe-sVKVci2O3GA" name="No" target="_WjDzYPkdEe-sVKVci2O3GA" source="_zeHNYPnhEe-6NbZI5Pt9YA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HiQGpPkdEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_HiQGpfkdEe-sVKVci2O3GA" name="validacionResutados" content="examinarMuestrasDAO.findByResultados('No Cirugia', 1, 1)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="expression:Expression" xmi:id="_SVkpwPniEe-6NbZI5Pt9YA" name="examinarMuestrasDAO" content="examinarMuestrasDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.ExaminarMuestrasDAO" returnTypeFixed="true"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dWPXYPkdEe-sVKVci2O3GA" target="_aUdocPkdEe-sVKVci2O3GA" source="_WjDzYPkdEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dWPXYfkdEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dWPXYvkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qDshcPkdEe-sVKVci2O3GA" name="Si" target="_kLXrYPpKEe-fE4P_wlxD9A" source="_zeHNYPnhEe-6NbZI5Pt9YA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qDshcfkdEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_qDshcvkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9fJ0kPkdEe-sVKVci2O3GA" target="_k0jLQPpKEe-fE4P_wlxD9A" source="_kLXrYPpKEe-fE4P_wlxD9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9fKboPkdEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_9fKbofkdEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VXVKoPkeEe-sVKVci2O3GA" target="_TC1_gPkeEe-sVKVci2O3GA" source="_k0jLQPpKEe-fE4P_wlxD9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VXVKofkeEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VXVKovkeEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Uj98UPnUEe-6NbZI5Pt9YA" target="_fwH9sPkOEe-sVKVci2O3GA" source="_uk3hYPkvEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Uj-jYPnUEe-6NbZI5Pt9YA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Uj-jYfnUEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZZ4owPncEe-6NbZI5Pt9YA" target="_PtIksPneEe-6NbZI5Pt9YA" source="_bkmz4PncEe-6NbZI5Pt9YA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZZ4owfncEe-6NbZI5Pt9YA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZZ4owvncEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Z-mfYPncEe-6NbZI5Pt9YA" name="Si" target="_bkmz4PncEe-6NbZI5Pt9YA" source="_ipYz8PmJEe-fP-Ja3oJY_g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Z-mfYfncEe-6NbZI5Pt9YA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Z-mfYvncEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eCjHEPoKEe-u9f6z6Vxoeg" target="_zeHNYPnhEe-6NbZI5Pt9YA" source="_fXj5cPkeEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eCjHEfoKEe-u9f6z6Vxoeg"/>
        <condition xmi:type="expression:Expression" xmi:id="_eCjHEvoKEe-u9f6z6Vxoeg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GWuW4PpKEe-fE4P_wlxD9A" target="_iq8acPpKEe-fE4P_wlxD9A" source="_7USKYPkbEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GWuW4fpKEe-fE4P_wlxD9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_GWuW4vpKEe-fE4P_wlxD9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4t1p4PpKEe-fE4P_wlxD9A" target="_fXj5cPkeEe-sVKVci2O3GA" source="_iq8acPpKEe-fE4P_wlxD9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4t1p4fpKEe-fE4P_wlxD9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_4t1p4vpKEe-fE4P_wlxD9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dn0iAPpOEe-fE4P_wlxD9A" target="_F7vmYPkeEe-sVKVci2O3GA" source="_TC1_gPkeEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dn1JEPpOEe-fE4P_wlxD9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_dn1JEfpOEe-fE4P_wlxD9A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gvs7gPqnEe-6RI7d5mZgpg" target="_ipYz8PmJEe-fP-Ja3oJY_g" source="_xvwMAPkOEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gvs7gfqnEe-6RI7d5mZgpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_gvs7gvqnEe-6RI7d5mZgpg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_vnxdwPkMEe-sVKVci2O3GA" name="Paciente" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_U8x2QPkWEe-sVKVci2O3GA" name="Medico"/>
      <actors xmi:type="process:Actor" xmi:id="_4Jae8PkdEe-sVKVci2O3GA" name="Hospitalario"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_IPhwYPnuEe-aK_fey8l7AQ" name="Production" version="8" username="Paciente">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_IPhwZvnuEe-aK_fey8l7AQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_IPhwZ_nuEe-aK_fey8l7AQ" name="Paciente">
            <groups xmi:type="actormapping:Groups" xmi:id="_IPhwaPnuEe-aK_fey8l7AQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_IPhwafnuEe-aK_fey8l7AQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_IPhwavnuEe-aK_fey8l7AQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_IPhwa_nuEe-aK_fey8l7AQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_IPhwbPnuEe-aK_fey8l7AQ" name="Medico">
            <groups xmi:type="actormapping:Groups" xmi:id="_IPhwbfnuEe-aK_fey8l7AQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_IPhwbvnuEe-aK_fey8l7AQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_IPhwb_nuEe-aK_fey8l7AQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_IPhwcPnuEe-aK_fey8l7AQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_IPhwcfnuEe-aK_fey8l7AQ" name="Hospitalario">
            <groups xmi:type="actormapping:Groups" xmi:id="_IPhwcvnuEe-aK_fey8l7AQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_IPhwc_nuEe-aK_fey8l7AQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_IPhwdPnuEe-aK_fey8l7AQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_IPhwdfnuEe-aK_fey8l7AQ"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IPhwYfnuEe-aK_fey8l7AQ" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IPhwYvnuEe-aK_fey8l7AQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IPhwY_nuEe-aK_fey8l7AQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IPhwZPnuEe-aK_fey8l7AQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IPhwZfnuEe-aK_fey8l7AQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_8kqAfPkLEe-sVKVci2O3GA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8kqAffkLEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_8kqAfvkLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8kqAf_kLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8kqAgPkLEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_8kqAgfkLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8kqAgvkLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8kqAg_kLEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_8kqAhPkLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8kqAhfkLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8kqAhvkLEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_8kqAh_kLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8kqAiPkLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8kqAifkLEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_8kqAivkLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8kqAi_kLEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_2JWUYPkMEe-sVKVci2O3GA" name="Aseguradora">
      <elements xmi:type="process:Lane" xmi:id="_sTug0PkREe-sVKVci2O3GA" name="Asegurador" actor="_xbOmIPkREe-sVKVci2O3GA">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_BYjTkPkUEe-sVKVci2O3GA" name="Recepción solicitud" outgoing="_cHLGoPqmEe-6RI7d5mZgpg" event="¿Solicitud de validación del paciente?" incomingMessag="_frgBwPkhEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BYjTkvkUEe-sVKVci2O3GA" name="Recepcion de solicitud" content="Recepcion de solicitud" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BYjTkfkUEe-sVKVci2O3GA" name="Recepcion de solicitud" content="Recepcion de solicitud" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BYjTk_kUEe-sVKVci2O3GA" name="Recepcion de solicitud" content="Recepcion de solicitud" returnTypeFixed="true"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_DB_e4PnKEe-LY4Y-wpuNyg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DCBUEfnKEe-LY4Y-wpuNyg" name="dataMessage" content="dataMessage" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_xkynMPnUEe-6NbZI5Pt9YA" name="dataMessage" dataType="_8kqAjvkLEe-sVKVci2O3GA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DCBUEPnKEe-LY4Y-wpuNyg" name="solicitudPaciente" content="solicitudPaciente" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_DB_e4fnKEe-LY4Y-wpuNyg" type="ASSIGNMENT"/>
          </messageContent>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_lBaocPkfEe-sVKVci2O3GA" name="Solicitar información paciente" outgoing="_cm-oEPqmEe-6RI7d5mZgpg" incoming="_cHLGoPqmEe-6RI7d5mZgpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lBaocvkfEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lBaocfkfEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lBaoc_kfEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_gVq-gPmBEe-fP-Ja3oJY_g" documentation="Solicitud de usuarios registrados y con seguro" name="getUsers" definitionId="rest-get" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_gVq-gfmBEe-fP-Ja3oJY_g" definitionId="rest-get" version="1.2.0" modelVersion="8">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-gvmBEe-fP-Ja3oJY_g" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-g_mBEe-fP-Ja3oJY_g" name="url()" content="'http://localhost:3000/data/patient/:' + dataMessage " interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_BLVuoAWkEfCQmuVCFen8jw" name="dataMessage" dataType="_8kqAjvkLEe-sVKVci2O3GA"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-hPmBEe-fP-Ja3oJY_g" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_gVq-hfmBEe-fP-Ja3oJY_g"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-hvmBEe-fP-Ja3oJY_g" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_gVq-h_mBEe-fP-Ja3oJY_g">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_gVq-iPmBEe-fP-Ja3oJY_g">
                    <expressions xmi:type="expression:Expression" xmi:id="_gVq-ifmBEe-fP-Ja3oJY_g" name="Content-type" content="Content-type"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_gVq-ivmBEe-fP-Ja3oJY_g" name="application/json" content="application/json"/>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-i_mBEe-fP-Ja3oJY_g" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-jPmBEe-fP-Ja3oJY_g" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-jfmBEe-fP-Ja3oJY_g" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-jvmBEe-fP-Ja3oJY_g" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-j_mBEe-fP-Ja3oJY_g" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-kPmBEe-fP-Ja3oJY_g" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-kfmBEe-fP-Ja3oJY_g" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-kvmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-k_mBEe-fP-Ja3oJY_g" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-lPmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-lfmBEe-fP-Ja3oJY_g" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-lvmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-l_mBEe-fP-Ja3oJY_g" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-mPmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-mfmBEe-fP-Ja3oJY_g" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-mvmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-m_mBEe-fP-Ja3oJY_g" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-nPmBEe-fP-Ja3oJY_g" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-nfmBEe-fP-Ja3oJY_g" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-nvmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-n_mBEe-fP-Ja3oJY_g" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-oPmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-ofmBEe-fP-Ja3oJY_g" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-ovmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-o_mBEe-fP-Ja3oJY_g" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-pPmBEe-fP-Ja3oJY_g" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-pfmBEe-fP-Ja3oJY_g" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-pvmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-p_mBEe-fP-Ja3oJY_g" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-qPmBEe-fP-Ja3oJY_g" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-qfmBEe-fP-Ja3oJY_g" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-qvmBEe-fP-Ja3oJY_g" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-q_mBEe-fP-Ja3oJY_g" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-rPmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-rfmBEe-fP-Ja3oJY_g" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-rvmBEe-fP-Ja3oJY_g" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-r_mBEe-fP-Ja3oJY_g" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-sPmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-sfmBEe-fP-Ja3oJY_g" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-svmBEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-s_mBEe-fP-Ja3oJY_g" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-tPmBEe-fP-Ja3oJY_g" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-tfmBEe-fP-Ja3oJY_g" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-tvmBEe-fP-Ja3oJY_g" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_gVq-t_mBEe-fP-Ja3oJY_g" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_gVq-uPmBEe-fP-Ja3oJY_g" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_gVq-ufmBEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gVq-uvmBEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gVq-u_mBEe-fP-Ja3oJY_g" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_gVq-vPmBEe-fP-Ja3oJY_g" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gVq-vfmBEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gVq-vvmBEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gVq-v_mBEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gVq-wPmBEe-fP-Ja3oJY_g" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_gVq-wfmBEe-fP-Ja3oJY_g" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gVq-wvmBEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gVq-w_mBEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gVq-xPmBEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gVq-xfmBEe-fP-Ja3oJY_g" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_gVq-xvmBEe-fP-Ja3oJY_g" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gVq-x_mBEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gVq-yPmBEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gVq-yfmBEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gVq-yvmBEe-fP-Ja3oJY_g" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_gVq-y_mBEe-fP-Ja3oJY_g" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gVq-zPmBEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_gVq-zfmBEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_gVq-zvmBEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_gVq-z_mBEe-fP-Ja3oJY_g" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_gVq-0PmBEe-fP-Ja3oJY_g" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_gVq-0fmBEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_ANvjUPmCEe-fP-Ja3oJY_g" name="getUser" definitionId="rest-get" event="ON_FINISH" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_ANvjUfmCEe-fP-Ja3oJY_g" definitionId="rest-get" version="1.2.0" modelVersion="8">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjUvmCEe-fP-Ja3oJY_g" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjU_mCEe-fP-Ja3oJY_g" name="url()" content="'http://localhost:3000/data/patient/:' + dataMessage " interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_DguRoAWkEfCQmuVCFen8jw" name="dataMessage" dataType="_8kqAjvkLEe-sVKVci2O3GA"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjVPmCEe-fP-Ja3oJY_g" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_ANvjVfmCEe-fP-Ja3oJY_g"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjVvmCEe-fP-Ja3oJY_g" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_ANvjV_mCEe-fP-Ja3oJY_g">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_ANvjWPmCEe-fP-Ja3oJY_g">
                    <expressions xmi:type="expression:Expression" xmi:id="_ANvjWfmCEe-fP-Ja3oJY_g" name="Content-Type" content="Content-Type"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_ANvjWvmCEe-fP-Ja3oJY_g" name="application/json" content="application/json"/>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjW_mCEe-fP-Ja3oJY_g" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjXPmCEe-fP-Ja3oJY_g" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjXfmCEe-fP-Ja3oJY_g" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjXvmCEe-fP-Ja3oJY_g" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjX_mCEe-fP-Ja3oJY_g" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjYPmCEe-fP-Ja3oJY_g" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjYfmCEe-fP-Ja3oJY_g" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjYvmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjY_mCEe-fP-Ja3oJY_g" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjZPmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjZfmCEe-fP-Ja3oJY_g" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjZvmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjZ_mCEe-fP-Ja3oJY_g" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjaPmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjafmCEe-fP-Ja3oJY_g" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjavmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvja_mCEe-fP-Ja3oJY_g" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjbPmCEe-fP-Ja3oJY_g" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjbfmCEe-fP-Ja3oJY_g" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjbvmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjb_mCEe-fP-Ja3oJY_g" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjcPmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjcfmCEe-fP-Ja3oJY_g" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjcvmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjc_mCEe-fP-Ja3oJY_g" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjdPmCEe-fP-Ja3oJY_g" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjdfmCEe-fP-Ja3oJY_g" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjdvmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjd_mCEe-fP-Ja3oJY_g" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjePmCEe-fP-Ja3oJY_g" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjefmCEe-fP-Ja3oJY_g" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjevmCEe-fP-Ja3oJY_g" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvje_mCEe-fP-Ja3oJY_g" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjfPmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjffmCEe-fP-Ja3oJY_g" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjfvmCEe-fP-Ja3oJY_g" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjf_mCEe-fP-Ja3oJY_g" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjgPmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjgfmCEe-fP-Ja3oJY_g" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjgvmCEe-fP-Ja3oJY_g" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjg_mCEe-fP-Ja3oJY_g" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjhPmCEe-fP-Ja3oJY_g" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjhfmCEe-fP-Ja3oJY_g" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjhvmCEe-fP-Ja3oJY_g" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANvjh_mCEe-fP-Ja3oJY_g" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_ANvjiPmCEe-fP-Ja3oJY_g" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_ANvjifmCEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_ANvjivmCEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_ANvji_mCEe-fP-Ja3oJY_g" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_ANvjjPmCEe-fP-Ja3oJY_g" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_ANvjjfmCEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_ANvjjvmCEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_ANvjj_mCEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_ANvjkPmCEe-fP-Ja3oJY_g" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_ANvjkfmCEe-fP-Ja3oJY_g" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_ANvjkvmCEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_ANvjk_mCEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_ANvjlPmCEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_ANvjlfmCEe-fP-Ja3oJY_g" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_ANvjlvmCEe-fP-Ja3oJY_g" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_ANvjl_mCEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_ANvjmPmCEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_ANvjmfmCEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_ANvjmvmCEe-fP-Ja3oJY_g" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_ANvjm_mCEe-fP-Ja3oJY_g" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_ANvjnPmCEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_ANvjnfmCEe-fP-Ja3oJY_g">
              <leftOperand xmi:type="expression:Expression" xmi:id="_ANvjnvmCEe-fP-Ja3oJY_g"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_ANvjn_mCEe-fP-Ja3oJY_g" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_ANvjoPmCEe-fP-Ja3oJY_g" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_ANvjofmCEe-fP-Ja3oJY_g" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_eGRr8PnHEe-LY4Y-wpuNyg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_eGRr8fnHEe-LY4Y-wpuNyg" name="asegurado" content="asegurado" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_TJb6IPqnEe-6RI7d5mZgpg" name="asegurado" dataType="_8kqAjPkLEe-sVKVci2O3GA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_eGRr8vnHEe-LY4Y-wpuNyg" name="setServiceWorks" content="true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_eGRr8_nHEe-LY4Y-wpuNyg" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lBaodPkfEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lBaodfkfEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lBaodvkfEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lBaoePkfEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lBaod_kfEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateThrowMessageEvent" xmi:id="_trxm4PnXEe-6NbZI5Pt9YA" name="Enviar Respuesta" outgoing="_wpCpQPnXEe-6NbZI5Pt9YA" incoming="_cm-oEPqmEe-6RI7d5mZgpg" outgoingMessages="_3Lcw8PkUEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Yj9DMPkUEe-sVKVci2O3GA" name="Mensaje Aseguradora" content="Mensaje Aseguradora" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Yj8cIfkUEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Yj9DMfkUEe-sVKVci2O3GA" name="Validar asegurado" content="Validar asegurado" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_2B0PYPkUEe-sVKVci2O3GA" documentation="Usuario asegurado" name="El usuario se encuentra o no asegurado">
            <correlation xmi:type="process:Correlation" xmi:id="_2B0PYfkUEe-sVKVci2O3GA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_2B0PYvkUEe-sVKVci2O3GA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_3Lbi0PkUEe-sVKVci2O3GA" name="Hospitalización Curatio" content="Hospitalización Curatio"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_3LcJ4PkUEe-sVKVci2O3GA" name="Recepcion Respuesta" content="Recepcion Respuesta"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_2B0PZfkUEe-sVKVci2O3GA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_zhaF4PnJEe-LY4Y-wpuNyg">
                <expressions xmi:type="expression:Expression" xmi:id="_zhaF4fnJEe-LY4Y-wpuNyg" name="asegurado" content="asegurado" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_zhaF4vnJEe-LY4Y-wpuNyg" name="resultadoPaciente" content="asegurado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_dtxbkPqnEe-6RI7d5mZgpg" name="asegurado" dataType="_8kqAjPkLEe-sVKVci2O3GA"/>
                </expressions>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_vCqhUPnXEe-6NbZI5Pt9YA" name="Fin solicitud" incoming="_wpCpQPnXEe-6NbZI5Pt9YA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vCqhUvnXEe-6NbZI5Pt9YA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vCqhUfnXEe-6NbZI5Pt9YA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vCqhU_nXEe-6NbZI5Pt9YA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ZLksgPnHEe-LY4Y-wpuNyg" name="solicitudAseguradora" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.SolicitudPaciente">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ZLksgfnHEe-LY4Y-wpuNyg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_LQzlUPnIEe-LY4Y-wpuNyg" name="pacienteAsegurado" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.PacienteAsegurado">
        <defaultValue xmi:type="expression:Expression" xmi:id="_LQzlUfnIEe-LY4Y-wpuNyg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_PFf-8PnIEe-LY4Y-wpuNyg" name="pacienteAseguradoResult" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.PacienteAsegurado">
        <defaultValue xmi:type="expression:Expression" xmi:id="_PFf-8fnIEe-LY4Y-wpuNyg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_T_QjMPnIEe-LY4Y-wpuNyg" name="pacienteAseguradoResults" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.PacienteAsegurado">
        <defaultValue xmi:type="expression:Expression" xmi:id="_T_QjMfnIEe-LY4Y-wpuNyg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_JG68IPnSEe-LY4Y-wpuNyg" name="datosMensajeAse" dataType="_8kqAkvkLEe-sVKVci2O3GA" className="java.util.List">
        <defaultValue xmi:type="expression:Expression" xmi:id="_JG68IfnSEe-LY4Y-wpuNyg" name="" content="" returnType="java.util.List"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_RoHhIPnSEe-LY4Y-wpuNyg" name="dataMessage" dataType="_8kqAjvkLEe-sVKVci2O3GA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_RoHhIfnSEe-LY4Y-wpuNyg" name="1" content="1" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_u62UAPnVEe-6NbZI5Pt9YA" name="asegurado" dataType="_8kqAjPkLEe-sVKVci2O3GA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_u62UAfnVEe-6NbZI5Pt9YA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_2JWUcPkMEe-sVKVci2O3GA">
        <targetForm xmi:type="expression:Expression" xmi:id="_u38AAPl_Ee-fP-Ja3oJY_g" name="Aseguradora" content="e9edd440-34a3-462c-9df5-2b78779b06e2" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_2JWUcvkMEe-sVKVci2O3GA">
        <targetForm xmi:type="expression:Expression" xmi:id="_r9nDoPnREe-LY4Y-wpuNyg" name="ResumenAseguradora" content="1c536f6b-8b5f-4d37-8338-6a3391405da0" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wpCpQPnXEe-6NbZI5Pt9YA" target="_vCqhUPnXEe-6NbZI5Pt9YA" source="_trxm4PnXEe-6NbZI5Pt9YA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wpCpQfnXEe-6NbZI5Pt9YA"/>
        <condition xmi:type="expression:Expression" xmi:id="_wpCpQvnXEe-6NbZI5Pt9YA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cHLGoPqmEe-6RI7d5mZgpg" target="_lBaocPkfEe-sVKVci2O3GA" source="_BYjTkPkUEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cHLtsPqmEe-6RI7d5mZgpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_cHLtsfqmEe-6RI7d5mZgpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cm-oEPqmEe-6RI7d5mZgpg" target="_trxm4PnXEe-6NbZI5Pt9YA" source="_lBaocPkfEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cm-oEfqmEe-6RI7d5mZgpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_cm-oEvqmEe-6RI7d5mZgpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_xbOmIPkREe-sVKVci2O3GA" documentation="Tiene la información de aseguradora del paciente" name="Asegurador" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_ILjPUPnuEe-aK_fey8l7AQ" name="Production" version="8" username="Paciente">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_ILj2YPnuEe-aK_fey8l7AQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_ILj2YfnuEe-aK_fey8l7AQ" name="Asegurador">
            <groups xmi:type="actormapping:Groups" xmi:id="_ILj2YvnuEe-aK_fey8l7AQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_ILj2Y_nuEe-aK_fey8l7AQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_ILj2ZPnuEe-aK_fey8l7AQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_ILj2ZfnuEe-aK_fey8l7AQ"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_ILjPUfnuEe-aK_fey8l7AQ" type="CONNECTOR" definitionId="rest-get" definitionVersion="1.2.0" implementationId="rest-get-impl" implementationVersion="1.3.2"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_ILjPUvnuEe-aK_fey8l7AQ" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_ILjPU_nuEe-aK_fey8l7AQ" id="rest-get-impl-1.3.2">
            <fragments xmi:type="configuration:Fragment" xmi:id="_ILjPVPnuEe-aK_fey8l7AQ" key="rest-get-impl -- 1.3.2" value="bonita-connector-rest-1.3.2.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_ILjPVfnuEe-aK_fey8l7AQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_ILjPVvnuEe-aK_fey8l7AQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_ILjPV_nuEe-aK_fey8l7AQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_ILjPWPnuEe-aK_fey8l7AQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_2JWUdPkMEe-sVKVci2O3GA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2JWUYfkMEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_2JWUYvkMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2JWUY_kMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2JWUZPkMEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_2JWUZfkMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2JWUZvkMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2JWUZ_kMEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_2JWUaPkMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2JWUafkMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2JWUavkMEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_2JWUa_kMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2JWUbPkMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2JWUbfkMEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_2JWUbvkMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2JWUb_kMEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_AUjCcPkgEe-sVKVci2O3GA" name="Laboratorio">
      <elements xmi:type="process:Lane" xmi:id="_Oi27QPkgEe-sVKVci2O3GA" name="Laboratorista" actor="_K5iEIPkgEe-sVKVci2O3GA">
        <elements xmi:type="process:StartEvent" xmi:id="_S6OkIPkgEe-sVKVci2O3GA" name="Realizar muestas" outgoing="_V9TTkfkgEe-sVKVci2O3GA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_S6OkIvkgEe-sVKVci2O3GA" name="Realizar muestras" content="Realizar muestras" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_S6OkIfkgEe-sVKVci2O3GA" name="Realizar muestras" content="Realizar muestras" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_S6OkI_kgEe-sVKVci2O3GA" name="Realizar muestras" content="Realizar muestras" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_X4zW8PkgEe-sVKVci2O3GA" name="Analizar muestras" outgoing="_PGJjAAWsEfCQmuVCFen8jw" incoming="_V9TTkfkgEe-sVKVci2O3GA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_V9SsgvkgEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_V9SsgfkgEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_V9Ssg_kgEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_CHe4tAWiEfCQmuVCFen8jw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_CHe4tQWiEfCQmuVCFen8jw" name="examinarMuestras" content="examinarMuestras" type="TYPE_VARIABLE" returnType="com.company.model.ExaminarMuestras">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_CHe4tgWiEfCQmuVCFen8jw" name="examinarMuestras" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_CHe4twWiEfCQmuVCFen8jw" name="examinarMuestrasInput.id" content="examinarMuestrasInput?.id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_CHe4uAWiEfCQmuVCFen8jw" name="examinarMuestrasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_CHe4uQWiEfCQmuVCFen8jw" type="JAVA_METHOD" expression="setId">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_CHe4ugWiEfCQmuVCFen8jw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_CHe4uwWiEfCQmuVCFen8jw" name="examinarMuestras" content="examinarMuestras" type="TYPE_VARIABLE" returnType="com.company.model.ExaminarMuestras">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_CHe4vAWiEfCQmuVCFen8jw" name="examinarMuestras" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_CHe4vQWiEfCQmuVCFen8jw" name="examinarMuestrasInput.nombreMuestra" content="examinarMuestrasInput?.nombreMuestra" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_CHe4vgWiEfCQmuVCFen8jw" name="examinarMuestrasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_CHe4vwWiEfCQmuVCFen8jw" type="JAVA_METHOD" expression="setNombreMuestra">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_CHe4wAWiEfCQmuVCFen8jw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_CHe4wQWiEfCQmuVCFen8jw" name="examinarMuestras" content="examinarMuestras" type="TYPE_VARIABLE" returnType="com.company.model.ExaminarMuestras">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_CHe4wgWiEfCQmuVCFen8jw" name="examinarMuestras" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_CHe4wwWiEfCQmuVCFen8jw" name="examinarMuestrasInput.consistencia" content="examinarMuestrasInput?.consistencia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_CHe4xAWiEfCQmuVCFen8jw" name="examinarMuestrasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_CHe4xQWiEfCQmuVCFen8jw" type="JAVA_METHOD" expression="setConsistencia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_V9SshPkgEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_V9SshfkgEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_V9SshvkgEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_V9SsiPkgEe-sVKVci2O3GA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_V9Ssh_kgEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_X4z-AfkgEe-sVKVci2O3GA" type="URL" url="http://localhost:4200/analizarMuestras">
            <targetForm xmi:type="expression:Expression" xmi:id="_6mxuoPngEe-6NbZI5Pt9YA" name="AnalizarMuestras" content="0f1db990-9684-49b6-b58a-bf1d18e7ddd1" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_X4z-APkgEe-sVKVci2O3GA">
            <inputs xmi:type="process:ContractInput" xmi:id="_CHe4sAWiEfCQmuVCFen8jw" name="examinarMuestrasInput" type="COMPLEX" dataReference="examinarMuestras" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_CHe4sQWiEfCQmuVCFen8jw" name="id" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_CHe4sgWiEfCQmuVCFen8jw" name="nombreMuestra" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_CHe4swWiEfCQmuVCFen8jw" name="consistencia" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_X4z-A_kgEe-sVKVci2O3GA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_f9tokPkgEe-sVKVci2O3GA" name="Entregar resultados" incoming="_7tx3sPpIEe-fE4P_wlxD9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f9tokvkgEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f9tokfkgEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f9tok_kgEe-sVKVci2O3GA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_M0hoIPpHEe-fE4P_wlxD9A" name="Esperar tiempo de resultados" outgoing="_7tx3sPpIEe-fE4P_wlxD9A" incoming="_Pi5wcAWsEfCQmuVCFen8jw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_M0hoIvpHEe-fE4P_wlxD9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_M0hoIfpHEe-fE4P_wlxD9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_M0hoI_pHEe-fE4P_wlxD9A" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_OHgS8PpHEe-fE4P_wlxD9A" name="00:00:01" content="1000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_LiKe4AWsEfCQmuVCFen8jw" name="Examinar Muestras" outgoing="_Pi5wcAWsEfCQmuVCFen8jw" incoming="_PGJjAAWsEfCQmuVCFen8jw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LiZIYAWsEfCQmuVCFen8jw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LiYhUAWsEfCQmuVCFen8jw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LiZIYQWsEfCQmuVCFen8jw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_R68l4wWsEfCQmuVCFen8jw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_R68l5AWsEfCQmuVCFen8jw" name="examinarMuestras" content="examinarMuestras" type="TYPE_VARIABLE" returnType="com.company.model.ExaminarMuestras">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_R68l5QWsEfCQmuVCFen8jw" name="examinarMuestras" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_R68l5gWsEfCQmuVCFen8jw" name="examinarMuestrasInput.nombreProcedimiento" content="examinarMuestrasInput?.nombreProcedimiento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_R68l5wWsEfCQmuVCFen8jw" name="examinarMuestrasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_R68l6AWsEfCQmuVCFen8jw" type="JAVA_METHOD" expression="setNombreProcedimiento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_R68l6QWsEfCQmuVCFen8jw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_R68l6gWsEfCQmuVCFen8jw" name="examinarMuestras" content="examinarMuestras" type="TYPE_VARIABLE" returnType="com.company.model.ExaminarMuestras">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_R68l6wWsEfCQmuVCFen8jw" name="examinarMuestras" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_R68l7AWsEfCQmuVCFen8jw" name="examinarMuestrasInput.resultados" content="examinarMuestrasInput?.resultados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_R68l7QWsEfCQmuVCFen8jw" name="examinarMuestrasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_R68l7gWsEfCQmuVCFen8jw" type="JAVA_METHOD" expression="setResultados">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LiZIYgWsEfCQmuVCFen8jw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LiZIYwWsEfCQmuVCFen8jw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LiZIZAWsEfCQmuVCFen8jw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LiZIZgWsEfCQmuVCFen8jw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_LiZIZQWsEfCQmuVCFen8jw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_LiZvcAWsEfCQmuVCFen8jw" type="URL" url="http://localhost:4200/examinarMuestras">
            <targetForm xmi:type="expression:Expression" xmi:id="_S_sAYAWsEfCQmuVCFen8jw" name="newForm" content="49e6f71d-9af2-400c-ab88-f9bf924389b4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_LiZIZwWsEfCQmuVCFen8jw">
            <inputs xmi:type="process:ContractInput" xmi:id="_R68l4AWsEfCQmuVCFen8jw" name="examinarMuestrasInput" type="COMPLEX" dataReference="examinarMuestras" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_R68l4QWsEfCQmuVCFen8jw" name="nombreProcedimiento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_R68l4gWsEfCQmuVCFen8jw" name="resultados" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_LiZvcgWsEfCQmuVCFen8jw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_YwxVgPo4Ee-fE4P_wlxD9A" name="necesarioCirugia" dataType="_8kqAjPkLEe-sVKVci2O3GA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_YwxVgfo4Ee-fE4P_wlxD9A" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="__M2TkAWhEfCQmuVCFen8jw" name="examinarMuestras" dataType="_8kqAlPkLEe-sVKVci2O3GA" className="com.company.model.ExaminarMuestras">
        <defaultValue xmi:type="expression:Expression" xmi:id="__M26oAWhEfCQmuVCFen8jw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_AUjpj_kgEe-sVKVci2O3GA">
        <targetForm xmi:type="expression:Expression" xmi:id="_D_Gv8PnhEe-6NbZI5Pt9YA" name="FormularioLaboratorio" content="ef247437-172e-43dc-ab3e-accba7b06829" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_AUjpkfkgEe-sVKVci2O3GA">
        <targetForm xmi:type="expression:Expression" xmi:id="_B3QSoPnhEe-6NbZI5Pt9YA" name="ResumenLaboratorio" content="1ad2d509-2a55-48c5-a712-acafb4b4fdfc" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_V9TTkfkgEe-sVKVci2O3GA" target="_X4zW8PkgEe-sVKVci2O3GA" source="_S6OkIPkgEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_V9TTkvkgEe-sVKVci2O3GA"/>
        <condition xmi:type="expression:Expression" xmi:id="_V9TTk_kgEe-sVKVci2O3GA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7tx3sPpIEe-fE4P_wlxD9A" target="_f9tokPkgEe-sVKVci2O3GA" source="_M0hoIPpHEe-fE4P_wlxD9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7tyewPpIEe-fE4P_wlxD9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_7tyewfpIEe-fE4P_wlxD9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PGJjAAWsEfCQmuVCFen8jw" target="_LiKe4AWsEfCQmuVCFen8jw" source="_X4zW8PkgEe-sVKVci2O3GA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PGKKEAWsEfCQmuVCFen8jw"/>
        <condition xmi:type="expression:Expression" xmi:id="_PGKKEQWsEfCQmuVCFen8jw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pi5wcAWsEfCQmuVCFen8jw" target="_M0hoIPpHEe-fE4P_wlxD9A" source="_LiKe4AWsEfCQmuVCFen8jw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pi5wcQWsEfCQmuVCFen8jw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pi5wcgWsEfCQmuVCFen8jw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_K5iEIPkgEe-sVKVci2O3GA" name="Laboratorista"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_IRffQPnuEe-aK_fey8l7AQ" name="Production" version="8" username="Paciente">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_IRffRvnuEe-aK_fey8l7AQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_IRffR_nuEe-aK_fey8l7AQ" name="Laboratorista">
            <groups xmi:type="actormapping:Groups" xmi:id="_IRffSPnuEe-aK_fey8l7AQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_IRffSfnuEe-aK_fey8l7AQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_IRffSvnuEe-aK_fey8l7AQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_IRffS_nuEe-aK_fey8l7AQ"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IRffQfnuEe-aK_fey8l7AQ" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IRffQvnuEe-aK_fey8l7AQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IRffQ_nuEe-aK_fey8l7AQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IRffRPnuEe-aK_fey8l7AQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_IRffRfnuEe-aK_fey8l7AQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_AUjpk_kgEe-sVKVci2O3GA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AUjpgPkgEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_AUjpgfkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AUjpgvkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AUjpg_kgEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_AUjphPkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AUjphfkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AUjphvkgEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_AUjph_kgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AUjpiPkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AUjpifkgEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_AUjpivkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AUjpi_kgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_AUjpjPkgEe-sVKVci2O3GA">
        <name xmi:type="expression:Expression" xmi:id="_AUjpjfkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_AUjpjvkgEe-sVKVci2O3GA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_8kqAjPkLEe-sVKVci2O3GA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_8kqAjfkLEe-sVKVci2O3GA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_8kqAjvkLEe-sVKVci2O3GA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_8kqAj_kLEe-sVKVci2O3GA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_8kqAkPkLEe-sVKVci2O3GA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_8kqAkfkLEe-sVKVci2O3GA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_8kqAkvkLEe-sVKVci2O3GA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_8kqAk_kLEe-sVKVci2O3GA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_8kqAlPkLEe-sVKVci2O3GA" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_3Lcw8PkUEe-sVKVci2O3GA" name="El usuario se encuentra o no asegurado" target="_xvwMAPkOEe-sVKVci2O3GA" source="_trxm4PnXEe-6NbZI5Pt9YA"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_frgBwPkhEe-sVKVci2O3GA" name="¿Solicitud de validación del paciente?" target="_BYjTkPkUEe-sVKVci2O3GA" source="_fwH9sPkOEe-sVKVci2O3GA"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_8kqAlfkLEe-sVKVci2O3GA" type="Process" element="_8kqAYPkLEe-sVKVci2O3GA" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_2JXigPkMEe-sVKVci2O3GA" type="2007" element="_2JWUYPkMEe-sVKVci2O3GA">
      <children xmi:type="notation:DecorationNode" xmi:id="_2JYJkPkMEe-sVKVci2O3GA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_2JYJkfkMEe-sVKVci2O3GA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_sTug0fkREe-sVKVci2O3GA" type="3007" element="_sTug0PkREe-sVKVci2O3GA">
          <children xmi:type="notation:DecorationNode" xmi:id="_sTug1vkREe-sVKVci2O3GA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_sTug1_kREe-sVKVci2O3GA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_BYj6oPkUEe-sVKVci2O3GA" type="3012" element="_BYjTkPkUEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_BYj6ovkUEe-sVKVci2O3GA" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BYj6o_kUEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BYj6ofkUEe-sVKVci2O3GA" x="102" y="114"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lBbPgPkfEe-sVKVci2O3GA" type="3027" element="_lBaocPkfEe-sVKVci2O3GA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lBbPgvkfEe-sVKVci2O3GA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lBbPgfkfEe-sVKVci2O3GA" x="345" y="111" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tryN8_nXEe-6NbZI5Pt9YA" type="3014" element="_trxm4PnXEe-6NbZI5Pt9YA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_tryN9fnXEe-6NbZI5Pt9YA" type="5030">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_tryN9vnXEe-6NbZI5Pt9YA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tryN9PnXEe-6NbZI5Pt9YA" x="756" y="128" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vCrIYPnXEe-6NbZI5Pt9YA" type="3003" element="_vCqhUPnXEe-6NbZI5Pt9YA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vCrIYvnXEe-6NbZI5Pt9YA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vCrIY_nXEe-6NbZI5Pt9YA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vCrIYfnXEe-6NbZI5Pt9YA" x="901" y="128"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_sTug0vkREe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_sTug0_kREe-sVKVci2O3GA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_sTug1PkREe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_sTug2PkREe-sVKVci2O3GA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sTug1fkREe-sVKVci2O3GA" x="96" y="135"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_2JXigfkMEe-sVKVci2O3GA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_2JXigvkMEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_2JXig_kMEe-sVKVci2O3GA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_2JYJkvkMEe-sVKVci2O3GA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2JXihPkMEe-sVKVci2O3GA" width="1073" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_8kqAlvkLEe-sVKVci2O3GA" type="2007" element="_8kqAYfkLEe-sVKVci2O3GA">
      <children xmi:type="notation:DecorationNode" xmi:id="_8kqAl_kLEe-sVKVci2O3GA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_8kqAmPkLEe-sVKVci2O3GA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_8kqAmfkLEe-sVKVci2O3GA" type="3007" element="_8kqAYvkLEe-sVKVci2O3GA">
          <children xmi:type="notation:DecorationNode" xmi:id="_8kqAmvkLEe-sVKVci2O3GA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8kqAm_kLEe-sVKVci2O3GA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_8kqAn_kLEe-sVKVci2O3GA" type="3002" element="_8kqAY_kLEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8kqAoPkLEe-sVKVci2O3GA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8kqAofkLEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8kqAovkLEe-sVKVci2O3GA" x="72" y="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fwIkw_kOEe-sVKVci2O3GA" type="3014" element="_fwH9sPkOEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fwIkxfkOEe-sVKVci2O3GA" type="5030">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fwIkxvkOEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fwIkxPkOEe-sVKVci2O3GA" x="319" y="70" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xvwMBPkOEe-sVKVci2O3GA" type="3013" element="_xvwMAPkOEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_xvwMBvkOEe-sVKVci2O3GA" type="5027">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xvwMB_kOEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xvwMBfkOEe-sVKVci2O3GA" x="471" y="70" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Y5XdE_kVEe-sVKVci2O3GA" type="3003" element="_Y5W2APkVEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Y5YEIPkVEe-sVKVci2O3GA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Y5YEIfkVEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y5XdFPkVEe-sVKVci2O3GA" x="936" y="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uk4Ic_kvEe-sVKVci2O3GA" type="3005" element="_uk3hYPkvEe-sVKVci2O3GA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uk4IdfkvEe-sVKVci2O3GA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uk4IdPkvEe-sVKVci2O3GA" x="166" y="56" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ipZbAPmJEe-fP-Ja3oJY_g" type="3008" element="_ipYz8PmJEe-fP-Ja3oJY_g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ipZbAvmJEe-fP-Ja3oJY_g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ipZbA_mJEe-fP-Ja3oJY_g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ipZbAfmJEe-fP-Ja3oJY_g" x="635" y="64" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8kqAo_kLEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8kqApPkLEe-sVKVci2O3GA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8kqApfkLEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8kqApvkLEe-sVKVci2O3GA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8kqAp_kLEe-sVKVci2O3GA"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Mw3kwPkWEe-sVKVci2O3GA" type="3007" element="_Mw29sPkWEe-sVKVci2O3GA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Mw3kxfkWEe-sVKVci2O3GA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Mw3kxvkWEe-sVKVci2O3GA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_5aX0sPkWEe-sVKVci2O3GA" type="3020" element="_5aXNoPkWEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5aX0svkWEe-sVKVci2O3GA" type="5035">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5aX0s_kWEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5aX0sfkWEe-sVKVci2O3GA" x="1364" y="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Lt8SsPkXEe-sVKVci2O3GA" type="3005" element="_Lt7roPkXEe-sVKVci2O3GA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Lt8SsvkXEe-sVKVci2O3GA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Lt8SsfkXEe-sVKVci2O3GA" x="837" y="183" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7USKa_kbEe-sVKVci2O3GA" type="3063" element="_7USKYPkbEe-sVKVci2O3GA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7USKbfkbEe-sVKVci2O3GA" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7USKbPkbEe-sVKVci2O3GA" x="1011" y="177" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WjEafPkdEe-sVKVci2O3GA" type="3005" element="_WjDzYPkdEe-sVKVci2O3GA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WjEafvkdEe-sVKVci2O3GA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WjEaffkdEe-sVKVci2O3GA" x="1666" y="185" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aUePg_kdEe-sVKVci2O3GA" type="3020" element="_aUdocPkdEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_aUePhfkdEe-sVKVci2O3GA" type="5035">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_aUePhvkdEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aUePhPkdEe-sVKVci2O3GA" x="1870" y="197"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fXkggPkeEe-sVKVci2O3GA" type="3017" element="_fXj5cPkeEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fXkggvkeEe-sVKVci2O3GA" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fXkgg_keEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fXkggfkeEe-sVKVci2O3GA" x="1418" y="191"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bkna-vncEe-6NbZI5Pt9YA" type="3005" element="_bkmz4PncEe-6NbZI5Pt9YA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bkna_PncEe-6NbZI5Pt9YA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bkna-_ncEe-6NbZI5Pt9YA" x="597" y="64" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PtJLwPneEe-6NbZI5Pt9YA" type="3008" element="_PtIksPneEe-6NbZI5Pt9YA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PtJLwvneEe-6NbZI5Pt9YA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PtJLw_neEe-6NbZI5Pt9YA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PtJLwfneEe-6NbZI5Pt9YA" x="863" y="72" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zeH0c_nhEe-6NbZI5Pt9YA" type="3008" element="_zeHNYPnhEe-6NbZI5Pt9YA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_zeH0dfnhEe-6NbZI5Pt9YA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zeH0dvnhEe-6NbZI5Pt9YA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zeH0dPnhEe-6NbZI5Pt9YA" x="1554" y="190" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iq9BiPpKEe-fE4P_wlxD9A" type="3006" element="_iq8acPpKEe-fE4P_wlxD9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iq9BivpKEe-fE4P_wlxD9A" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iq9BifpKEe-fE4P_wlxD9A" x="1200" y="179" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kLXrafpKEe-fE4P_wlxD9A" type="3006" element="_kLXrYPpKEe-fE4P_wlxD9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kLYScPpKEe-fE4P_wlxD9A" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kLXravpKEe-fE4P_wlxD9A" x="1524" y="356" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uartKfpMEe-fE4P_wlxD9A" type="3006" element="_uartIPpMEe-fE4P_wlxD9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uartK_pMEe-fE4P_wlxD9A" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uartKvpMEe-fE4P_wlxD9A" x="1098" y="69" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Mw3kwfkWEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Mw3kwvkWEe-sVKVci2O3GA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Mw3kw_kWEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Mw3kx_kWEe-sVKVci2O3GA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Mw3kxPkWEe-sVKVci2O3GA" x="48" y="250" width="1979" height="482"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_2usNYPkdEe-sVKVci2O3GA" type="3007" element="_2urmUPkdEe-sVKVci2O3GA">
          <children xmi:type="notation:DecorationNode" xmi:id="_2us0cPkdEe-sVKVci2O3GA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_2us0cfkdEe-sVKVci2O3GA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_F7wNc_keEe-sVKVci2O3GA" type="3020" element="_F7vmYPkeEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F7wNdfkeEe-sVKVci2O3GA" type="5035">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F7wNdvkeEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F7wNdPkeEe-sVKVci2O3GA" x="1877" y="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TC2mkPkeEe-sVKVci2O3GA" type="3017" element="_TC1_gPkeEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TC2mkvkeEe-sVKVci2O3GA" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TC2mk_keEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TC2mkfkeEe-sVKVci2O3GA" x="1725" y="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_k0jyWPpKEe-fE4P_wlxD9A" type="3006" element="_k0jLQPpKEe-fE4P_wlxD9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_k0jyWvpKEe-fE4P_wlxD9A" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k0jyWfpKEe-fE4P_wlxD9A" x="1499" y="42" width="124" height="61"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_2usNYfkdEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_2usNYvkdEe-sVKVci2O3GA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_2usNY_kdEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_2us0cvkdEe-sVKVci2O3GA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2usNZPkdEe-sVKVci2O3GA" x="48" y="732" width="1979" height="180"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_8kqAqPkLEe-sVKVci2O3GA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_8kqAqfkLEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_8kqAqvkLEe-sVKVci2O3GA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_8kqAq_kLEe-sVKVci2O3GA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8kqArPkLEe-sVKVci2O3GA" width="2002" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AUkQkPkgEe-sVKVci2O3GA" type="2007" element="_AUjCcPkgEe-sVKVci2O3GA">
      <children xmi:type="notation:DecorationNode" xmi:id="_AUkQlfkgEe-sVKVci2O3GA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_AUkQlvkgEe-sVKVci2O3GA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Oi27QfkgEe-sVKVci2O3GA" type="3007" element="_Oi27QPkgEe-sVKVci2O3GA">
          <children xmi:type="notation:DecorationNode" xmi:id="_Oi3iUPkgEe-sVKVci2O3GA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Oi3iUfkgEe-sVKVci2O3GA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_S6PLMPkgEe-sVKVci2O3GA" type="3002" element="_S6OkIPkgEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_S6PLMvkgEe-sVKVci2O3GA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_S6PLM_kgEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_S6PLMfkgEe-sVKVci2O3GA" x="53" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_X4z-BPkgEe-sVKVci2O3GA" type="3005" element="_X4zW8PkgEe-sVKVci2O3GA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_X4z-BvkgEe-sVKVci2O3GA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_X4z-BfkgEe-sVKVci2O3GA" x="141" y="99" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_f9uPoPkgEe-sVKVci2O3GA" type="3003" element="_f9tokPkgEe-sVKVci2O3GA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_f9uPovkgEe-sVKVci2O3GA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_f9uPo_kgEe-sVKVci2O3GA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f9uPofkgEe-sVKVci2O3GA" x="806" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M0iPMPpHEe-fE4P_wlxD9A" type="3017" element="_M0hoIPpHEe-fE4P_wlxD9A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_M0iPMvpHEe-fE4P_wlxD9A" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_M0iPM_pHEe-fE4P_wlxD9A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M0iPMfpHEe-fE4P_wlxD9A" x="612" y="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Lif2EAWsEfCQmuVCFen8jw" type="3005" element="_LiKe4AWsEfCQmuVCFen8jw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_LiiSUAWsEfCQmuVCFen8jw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Lif2EQWsEfCQmuVCFen8jw" x="373" y="100"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Oi27QvkgEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Oi27Q_kgEe-sVKVci2O3GA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Oi27RPkgEe-sVKVci2O3GA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Oi3iUvkgEe-sVKVci2O3GA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Oi27RfkgEe-sVKVci2O3GA" x="90" y="99"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_AUkQkfkgEe-sVKVci2O3GA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_AUkQkvkgEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_AUkQk_kgEe-sVKVci2O3GA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_AUkQl_kgEe-sVKVci2O3GA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AUkQlPkgEe-sVKVci2O3GA" width="1005" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_8kqArfkLEe-sVKVci2O3GA"/>
    <edges xmi:type="notation:Connector" xmi:id="_o2d3IPkOEe-sVKVci2O3GA" type="4001" element="_o2cpAPkOEe-sVKVci2O3GA" source="_8kqAn_kLEe-sVKVci2O3GA" target="_uk4Ic_kvEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_o2d3I_kOEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_o2d3JPkOEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_o2d3IfkOEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_o2d3IvkOEe-sVKVci2O3GA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_o2fFQPkOEe-sVKVci2O3GA" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_z8-RgfkOEe-sVKVci2O3GA" type="4001" element="_z89qcPkOEe-sVKVci2O3GA" source="_fwIkw_kOEe-sVKVci2O3GA" target="_xvwMBPkOEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_z8-RhPkOEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_z8-RhfkOEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_z8-RgvkOEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_z8-Rg_kOEe-sVKVci2O3GA" points="[-12, 1, -168, 14]$[162, -27, 6, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_z8_foPkOEe-sVKVci2O3GA" id="(1.0,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3Lcw8fkUEe-sVKVci2O3GA" type="4002" element="_3Lcw8PkUEe-sVKVci2O3GA" source="_tryN8_nXEe-6NbZI5Pt9YA" target="_xvwMBPkOEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3Lcw9PkUEe-sVKVci2O3GA" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3Lcw9fkUEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3Lcw8vkUEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3Lcw8_kUEe-sVKVci2O3GA" points="[-1, 14, 284, -198]$[-1, 73, 284, -139]$[-292, 73, -7, -139]$[-292, 198, -7, -14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l0dag_kVEe-sVKVci2O3GA" type="4001" element="_l0dagPkVEe-sVKVci2O3GA" source="_ipZbAPmJEe-fP-Ja3oJY_g" target="_Y5XdE_kVEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l0dahvkVEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l0dah_kVEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l0dahPkVEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l0dahfkVEe-sVKVci2O3GA" points="[-1, -8, -274, 0]$[258, -8, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_l0eooPkVEe-sVKVci2O3GA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xUAKg_kWEe-sVKVci2O3GA" type="4001" element="_xUAKgPkWEe-sVKVci2O3GA" source="_PtJLwPneEe-6NbZI5Pt9YA" target="_uartKfpMEe-fE4P_wlxD9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xUAKhvkWEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xUAKh_kWEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xUAKhPkWEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xUAKhfkWEe-sVKVci2O3GA" points="[-3, -9, -212, 0]$[192, -11, -17, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xUBYoPkWEe-sVKVci2O3GA" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xUBYofkWEe-sVKVci2O3GA" id="(0.17,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Enje0_kXEe-sVKVci2O3GA" type="4001" element="_Enje0PkXEe-sVKVci2O3GA" source="_uartKfpMEe-fE4P_wlxD9A" target="_5aX0sPkWEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EnkF4PkXEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EnkF4fkXEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Enje1PkXEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Enje1fkXEe-sVKVci2O3GA" points="[0, 1, -111, 1]$[112, -5, 1, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Enks8PkXEe-sVKVci2O3GA" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Enks8fkXEe-sVKVci2O3GA" id="(0.06666666666666667,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_O0RKc_kXEe-sVKVci2O3GA" type="4001" element="_O0RKcPkXEe-sVKVci2O3GA" source="_PtJLwPneEe-6NbZI5Pt9YA" target="_Lt8SsPkXEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_O0RKdvkXEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_O0RKd_kXEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_O0RKdPkXEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_O0RKdfkXEe-sVKVci2O3GA" points="[-15, 9, -1, -56]$[-13, 61, 1, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_O0RxgPkXEe-sVKVci2O3GA" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_O0RxgfkXEe-sVKVci2O3GA" id="(0.5,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6kMKM_kbEe-sVKVci2O3GA" type="4001" element="_6kMKMPkbEe-sVKVci2O3GA" source="_Lt8SsPkXEe-sVKVci2O3GA" target="_7USKa_kbEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6kMKNvkbEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6kMKN_kbEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6kMKNPkbEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6kMKNfkbEe-sVKVci2O3GA" points="[0, 0, -99, 1]$[100, 23, 1, 24]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6kMxQPkbEe-sVKVci2O3GA" id="(1.0,0.62)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6kMxQfkbEe-sVKVci2O3GA" id="(0.23015873015873015,0.49206349206349204)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HiQGpvkdEe-sVKVci2O3GA" type="4001" element="_HiQGo_kdEe-sVKVci2O3GA" source="_zeH0c_nhEe-6NbZI5Pt9YA" target="_WjEafPkdEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HiQGqfkdEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HiQGqvkdEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HiQGp_kdEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HiQGqPkdEe-sVKVci2O3GA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dWP-cPkdEe-sVKVci2O3GA" type="4001" element="_dWPXYPkdEe-sVKVci2O3GA" source="_WjEafPkdEe-sVKVci2O3GA" target="_aUePg_kdEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dWP-c_kdEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dWP-dPkdEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dWP-cfkdEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dWP-cvkdEe-sVKVci2O3GA" points="[0, 4, -58, 1]$[59, 5, 1, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dWQlgPkdEe-sVKVci2O3GA" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dWQlgfkdEe-sVKVci2O3GA" id="(0.03333333333333333,0.6666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qDshc_kdEe-sVKVci2O3GA" type="4001" element="_qDshcPkdEe-sVKVci2O3GA" source="_zeH0c_nhEe-6NbZI5Pt9YA" target="_kLXrafpKEe-fE4P_wlxD9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qDtIgPkdEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qDtIgfkdEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qDshdPkdEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qDshdfkdEe-sVKVci2O3GA" points="[-17, 10, 0, -111]$[-21, 102, -4, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qDtvkPkdEe-sVKVci2O3GA" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9fKbovkdEe-sVKVci2O3GA" type="4001" element="_9fJ0kPkdEe-sVKVci2O3GA" source="_kLXrafpKEe-fE4P_wlxD9A" target="_k0jyWPpKEe-fE4P_wlxD9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9fKbpfkdEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9fKbpvkdEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9fKbo_kdEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9fKbpPkdEe-sVKVci2O3GA" points="[-51, 22, 12, -149]$[-51, 140, 12, -31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9fLCsPkdEe-sVKVci2O3GA" id="(1.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VXVxsPkeEe-sVKVci2O3GA" type="4001" element="_VXVKoPkeEe-sVKVci2O3GA" source="_k0jyWPpKEe-fE4P_wlxD9A" target="_TC2mkPkeEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VXVxs_keEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VXVxtPkeEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VXVxsfkeEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VXVxsvkeEe-sVKVci2O3GA" points="[0, -1, -84, 1]$[85, 5, 1, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VXWYwPkeEe-sVKVci2O3GA" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VXWYwfkeEe-sVKVci2O3GA" id="(0.8333333333333334,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_V9TTlPkgEe-sVKVci2O3GA" type="4001" element="_V9TTkfkgEe-sVKVci2O3GA" source="_S6PLMPkgEe-sVKVci2O3GA" target="_X4z-BPkgEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_V9TTl_kgEe-sVKVci2O3GA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_V9TTmPkgEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_V9TTlfkgEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_V9TTlvkgEe-sVKVci2O3GA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_frgBwfkhEe-sVKVci2O3GA" type="4002" element="_frgBwPkhEe-sVKVci2O3GA" source="_fwIkw_kOEe-sVKVci2O3GA" target="_BYj6oPkUEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_frgBxPkhEe-sVKVci2O3GA" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_frgBxfkhEe-sVKVci2O3GA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_frgBwvkhEe-sVKVci2O3GA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_frgBw_khEe-sVKVci2O3GA" points="[-2, -15, 215, 211]$[-2, -139, 215, 87]$[-217, -139, 0, 87]$[-217, -212, 0, 14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Uj-jYvnUEe-6NbZI5Pt9YA" type="4001" element="_Uj98UPnUEe-6NbZI5Pt9YA" source="_uk4Ic_kvEe-sVKVci2O3GA" target="_fwIkw_kOEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Uj-jZfnUEe-6NbZI5Pt9YA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Uj_KcPnUEe-6NbZI5Pt9YA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Uj-jY_nUEe-6NbZI5Pt9YA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Uj-jZPnUEe-6NbZI5Pt9YA" points="[0, 0, -68, -2]$[72, -13, 4, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Uj_xgPnUEe-6NbZI5Pt9YA" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wpDQUPnXEe-6NbZI5Pt9YA" type="4001" element="_wpCpQPnXEe-6NbZI5Pt9YA" source="_tryN8_nXEe-6NbZI5Pt9YA" target="_vCrIYPnXEe-6NbZI5Pt9YA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wpDQU_nXEe-6NbZI5Pt9YA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wpDQVPnXEe-6NbZI5Pt9YA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wpDQUfnXEe-6NbZI5Pt9YA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wpDQUvnXEe-6NbZI5Pt9YA" points="[-12, 1, -142, 14]$[115, -13, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wpD3YPnXEe-6NbZI5Pt9YA" id="(1.0,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZZ4ow_ncEe-6NbZI5Pt9YA" type="4001" element="_ZZ4owPncEe-6NbZI5Pt9YA" source="_bkna-vncEe-6NbZI5Pt9YA" target="_PtJLwPneEe-6NbZI5Pt9YA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZZ4oxvncEe-6NbZI5Pt9YA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZZ4ox_ncEe-6NbZI5Pt9YA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZZ4oxPncEe-6NbZI5Pt9YA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZZ4oxfncEe-6NbZI5Pt9YA" points="[0, -1, -154, 0]$[147, -2, -7, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZZ5P0PncEe-6NbZI5Pt9YA" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZZ5P0fncEe-6NbZI5Pt9YA" id="(0.18604651162790697,0.46511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Z-smAPncEe-6NbZI5Pt9YA" type="4001" element="_Z-mfYPncEe-6NbZI5Pt9YA" source="_ipZbAPmJEe-fP-Ja3oJY_g" target="_bkna-vncEe-6NbZI5Pt9YA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Z-smA_ncEe-6NbZI5Pt9YA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Z-smBPncEe-6NbZI5Pt9YA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Z-smAfncEe-6NbZI5Pt9YA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Z-smAvncEe-6NbZI5Pt9YA" points="[-23, 12, -2, -237]$[-29, 279, -8, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Z-tNEPncEe-6NbZI5Pt9YA" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eCjHE_oKEe-u9f6z6Vxoeg" type="4001" element="_eCjHEPoKEe-u9f6z6Vxoeg" source="_fXkggPkeEe-sVKVci2O3GA" target="_zeH0c_nhEe-6NbZI5Pt9YA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eCjuIPoKEe-u9f6z6Vxoeg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eCjuIfoKEe-u9f6z6Vxoeg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eCjHFPoKEe-u9f6z6Vxoeg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eCjHFfoKEe-u9f6z6Vxoeg" points="[-1, -11, -99, -4]$[81, -11, -17, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_eCkVMPoKEe-u9f6z6Vxoeg" id="(1.0,0.9)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7tyewvpIEe-fE4P_wlxD9A" type="4001" element="_7tx3sPpIEe-fE4P_wlxD9A" source="_M0iPMPpHEe-fE4P_wlxD9A" target="_f9uPoPkgEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7tyexfpIEe-fE4P_wlxD9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7tyexvpIEe-fE4P_wlxD9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7tyew_pIEe-fE4P_wlxD9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7tyexPpIEe-fE4P_wlxD9A" points="[0, -12, -190, -1]$[186, -22, -4, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7tzF0PpIEe-fE4P_wlxD9A" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GWuW4_pKEe-fE4P_wlxD9A" type="4001" element="_GWuW4PpKEe-fE4P_wlxD9A" source="_7USKa_kbEe-sVKVci2O3GA" target="_iq9BiPpKEe-fE4P_wlxD9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GWuW5vpKEe-fE4P_wlxD9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GWuW5_pKEe-fE4P_wlxD9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GWuW5PpKEe-fE4P_wlxD9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GWuW5fpKEe-fE4P_wlxD9A" points="[0, -2, -78, 8]$[64, -2, -14, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GWu98PpKEe-fE4P_wlxD9A" id="(1.0,0.5645161290322581)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GWu98fpKEe-fE4P_wlxD9A" id="(0.11904761904761904,0.38095238095238093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4t2Q8PpKEe-fE4P_wlxD9A" type="4001" element="_4t1p4PpKEe-fE4P_wlxD9A" source="_iq9BiPpKEe-fE4P_wlxD9A" target="_fXkggPkeEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4t2Q8_pKEe-fE4P_wlxD9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4t2Q9PpKEe-fE4P_wlxD9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4t2Q8fpKEe-fE4P_wlxD9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4t2Q8vpKEe-fE4P_wlxD9A" points="[0, -3, -95, 1]$[96, -11, 1, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4t24APpKEe-fE4P_wlxD9A" id="(1.0,0.46774193548387094)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4t24AfpKEe-fE4P_wlxD9A" id="(0.16666666666666666,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dn1JEvpOEe-fE4P_wlxD9A" type="4001" element="_dn0iAPpOEe-fE4P_wlxD9A" source="_TC2mkPkeEe-sVKVci2O3GA" target="_F7wNc_keEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dn1JFfpOEe-fE4P_wlxD9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dn1JFvpOEe-fE4P_wlxD9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dn1JE_pOEe-fE4P_wlxD9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dn1JFPpOEe-fE4P_wlxD9A" points="[0, -14, -127, -2]$[122, -11, -5, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dn1wIPpOEe-fE4P_wlxD9A" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dn1wIfpOEe-fE4P_wlxD9A" id="(0.16666666666666666,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cHLtsvqmEe-6RI7d5mZgpg" type="4001" element="_cHLGoPqmEe-6RI7d5mZgpg" source="_BYj6oPkUEe-sVKVci2O3GA" target="_lBbPgPkfEe-sVKVci2O3GA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cHMUwPqmEe-6RI7d5mZgpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cHMUwfqmEe-6RI7d5mZgpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cHLts_qmEe-6RI7d5mZgpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cHLttPqmEe-6RI7d5mZgpg" points="[-2, -6, -225, 0]$[213, -8, -10, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cHM70PqmEe-6RI7d5mZgpg" id="(1.0,0.8666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cHM70fqmEe-6RI7d5mZgpg" id="(0.07936507936507936,0.36507936507936506)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cm_PIPqmEe-6RI7d5mZgpg" type="4001" element="_cm-oEPqmEe-6RI7d5mZgpg" source="_lBbPgPkfEe-sVKVci2O3GA" target="_tryN8_nXEe-6NbZI5Pt9YA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cm_PI_qmEe-6RI7d5mZgpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cm_PJPqmEe-6RI7d5mZgpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cm_PIfqmEe-6RI7d5mZgpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cm_PIvqmEe-6RI7d5mZgpg" points="[0, 1, -300, -5]$[293, -8, -7, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cm_2MPqmEe-6RI7d5mZgpg" id="(1.0,0.4126984126984127)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gvtikPqnEe-6RI7d5mZgpg" type="4001" element="_gvs7gPqnEe-6RI7d5mZgpg" source="_xvwMBPkOEe-sVKVci2O3GA" target="_ipZbAPmJEe-fP-Ja3oJY_g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gvtik_qnEe-6RI7d5mZgpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gvtilPqnEe-6RI7d5mZgpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gvtikfqnEe-6RI7d5mZgpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gvtikvqnEe-6RI7d5mZgpg" points="[0, -14, -142, -3]$[137, -11, -5, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gvuJoPqnEe-6RI7d5mZgpg" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gvuJofqnEe-6RI7d5mZgpg" id="(0.18604651162790697,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PGKxIAWsEfCQmuVCFen8jw" type="4001" element="_PGJjAAWsEfCQmuVCFen8jw" source="_X4z-BPkgEe-sVKVci2O3GA" target="_Lif2EAWsEfCQmuVCFen8jw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PGKxIwWsEfCQmuVCFen8jw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PGKxJAWsEfCQmuVCFen8jw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PGKxIQWsEfCQmuVCFen8jw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PGKxIgWsEfCQmuVCFen8jw" points="[0, 0, -141, -11]$[132, 9, -9, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PGN0cAWsEfCQmuVCFen8jw" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PGN0cQWsEfCQmuVCFen8jw" id="(0.09,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pi6XgAWsEfCQmuVCFen8jw" type="4001" element="_Pi5wcAWsEfCQmuVCFen8jw" source="_Lif2EAWsEfCQmuVCFen8jw" target="_M0iPMPpHEe-fE4P_wlxD9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pi6-kAWsEfCQmuVCFen8jw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pi6-kQWsEfCQmuVCFen8jw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pi6XgQWsEfCQmuVCFen8jw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pi6XggWsEfCQmuVCFen8jw" points="[0, 0, -154, 24]$[148, -11, -6, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Pi_3EAWsEfCQmuVCFen8jw" id="(1.0,0.56)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
